# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0003_documentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='advanced_permission',
            field=models.BooleanField(default=False, verbose_name='需要高级权限'),
        ),
        migrations.AddField(
            model_name='entry',
            name='generic_permission',
            field=models.BooleanField(default=False, verbose_name='需要一般权限'),
        ),
    ]
