# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0004_auto_20160215_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='css_style',
            field=models.CharField(choices=[('default', '默认'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')],
                                   default='default', max_length=255, verbose_name='css样式'),
        ),
    ]
