# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:39
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0005_entry_css_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-db_manual_order', '-db_modified'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='category',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='category',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='category',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='category',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='documentuser',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='documentuser',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='documentuser',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='documentuser',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
