# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0006_auto_20160215_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AlterField(
            model_name='entry',
            name='key_word',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='record',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'history': []}, editable=False, verbose_name='历史记录'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
