# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BusinessSystem', '0006_auto_20160220_0121'),
        ('Equipment', '0006_auto_20160220_0121'),
        ('Document', '0010_auto_20160220_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='relevant_business',
            field=models.ManyToManyField(blank=True, help_text='涉及的业务系统，没有请留空', related_name='relevant_document', to='BusinessSystem.System', verbose_name='涉及系统'),
        ),
        migrations.AddField(
            model_name='entry',
            name='relevant_equipment',
            field=models.ManyToManyField(blank=True, help_text='涉及的硬件设备类型，请尽量准确，没有请留空', related_name='relevant_document', to='Equipment.EquipmentModel', verbose_name='涉及硬件'),
        ),
    ]
