# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0011_auto_20160303_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentuser',
            options={'verbose_name': '文档系统用户', 'verbose_name_plural': '文档系统用户'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='advanced_permission',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='generic_permission',
        ),
        migrations.AddField(
            model_name='entry',
            name='require_advanced_permission',
            field=models.BooleanField(default=False, verbose_name='需要高级权限才可以浏览'),
        ),
        migrations.AddField(
            model_name='entry',
            name='require_generic_permission',
            field=models.BooleanField(default=False, verbose_name='需要一般权限可浏览、普通用户不行'),
        ),
    ]
