# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Document', '0012_auto_20160304_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='require_advanced_permission',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='require_generic_permission',
        ),
        migrations.AddField(
            model_name='entry',
            name='require_permission',
            field=models.IntegerField(choices=[(0, '访客可访问'), (1, '一般权限'), (2, '需要高级权限')], default=1, verbose_name='所需权限'),
        ),
    ]
