# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:42
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
            options={
                'verbose_name_plural': '地理区域',
                'verbose_name': '地理区域',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('for_short', models.CharField(max_length=255, verbose_name='缩写')),
                ('dot_code', models.CharField(max_length=255, unique=True, verbose_name='网点号')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchManager.Area', verbose_name='所在区域')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
            options={
                'verbose_name_plural': '部门/网点',
                'verbose_name': '部门/网点',
            },
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
            ],
            options={
                'verbose_name_plural': '部门分类',
                'verbose_name': '部门分类',
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('for_short', models.CharField(max_length=255, verbose_name='缩写')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchManager.Department', verbose_name='父级部门')),
            ],
            options={
                'verbose_name_plural': '二级部门',
                'verbose_name': '二级部门',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchManager.DepartmentType', verbose_name='部门分类'),
        ),
    ]
