# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('BranchManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='manager',
        ),
    ]
