# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BranchManager', '0006_auto_20160220_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='pinyin',
            field=models.CharField(default=' ', max_length=255, verbose_name='拼音'),
            preserve_default=False,
        ),
    ]
