# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchManager', '0007_department_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='office_hours_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='上班时间'),
        ),
        migrations.AddField(
            model_name='department',
            name='office_hours_stop',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='下班时间'),
        ),
    ]
