# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:36
from __future__ import unicode_literals

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Equipment', '0002_auto_20160215_1639'),
        ('BusinessSystem', '0002_auto_20160215_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BranchManager', '0003_auto_20160215_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketSystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, verbose_name='顺位')),
                ('is_watcher', models.BooleanField(default=False, verbose_name='是值班员（有登记权限）')),
                ('is_worker', models.BooleanField(default=False, verbose_name='员工')),
                ('is_admin', models.BooleanField(default=False, verbose_name='完全管理员')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_system_user', to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '工单系统用户',
                'verbose_name_plural': '工单系统用户',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=127, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, verbose_name='顺位')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(default={'name': None, 'telephone': None}, verbose_name='联系人')),
                ('level', models.FloatField(default=0.0, verbose_name='故障级别')),
                ('incidence', models.FloatField(choices=[(0.0, '一个人'), (1.0, '多个人'), (2.0, '一个部门'), (3.0, '一个网点/多个部门')], default=0.0, verbose_name='影响范围')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket', to='SupportTicketSystem.SupportTicketSystemUser',
                                              verbose_name='创建者')),
                ('department',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_ticket', to='BranchManager.Department', verbose_name='网点/部门')),
                ('relevant_business', models.ManyToManyField(blank=True, related_name='relevant_ticket', to='BusinessSystem.System', verbose_name='涉及系统')),
                ('relevant_equipment', models.ManyToManyField(blank=True, related_name='relevant_ticket', to='Equipment.EquipmentModel', verbose_name='涉及硬件')),
                ('tag', models.ManyToManyField(blank=True, related_name='ticket', to='SupportTicketSystem.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=127, verbose_name='现象')),
            ],
            options={
                'verbose_name': '故障现象',
                'verbose_name_plural': '故障现象',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='troubles',
            field=models.ManyToManyField(related_name='ticket', to='SupportTicketSystem.Trouble', verbose_name='故障现象'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_ticket', to='SupportTicketSystem.SupportTicketSystemUser',
                                    verbose_name='责任人'),
        ),
    ]
