# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 17:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0005_auto_20160217_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='process',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'log': {'data': [], 'status': None}, 'workflow': {'data': [], 'status': None}}, verbose_name='处理信息'),
        ),
    ]
