# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0006_ticket_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='for_short',
            field=models.CharField(default=1, max_length=127, verbose_name='缩写'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticketsystemuser',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位'),
        ),
    ]
