# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0009_auto_20160218_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='for_short',
            field=models.CharField(default=' ', max_length=24, verbose_name='缩写'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='for_short',
            field=models.CharField(default=' ', max_length=24, verbose_name='缩写'),
        ),
    ]
