# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0010_auto_20160218_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='relevant_business',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='relevant_equipment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='troubles',
        ),
    ]
