# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Equipment', '0005_auto_20160219_1118'),
        ('BusinessSystem', '0005_system_db_active'),
        ('SupportTicketSystem', '0011_auto_20160219_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketsystemuser',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='tag',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='relevant_business',
            field=models.ManyToManyField(blank=True, related_name='relevant_ticket', to='BusinessSystem.System', verbose_name='涉及系统'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='relevant_equipment',
            field=models.ManyToManyField(blank=True, related_name='relevant_ticket', to='Equipment.EquipmentModel', verbose_name='涉及硬件'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='ticket', to='SupportTicketSystem.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='troubles',
            field=models.ManyToManyField(related_name='ticket', to='SupportTicketSystem.Trouble', verbose_name='故障现象'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
    ]
