# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0013_ticket_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_ticket',
                                    to='SupportTicketSystem.SupportTicketSystemUser', verbose_name='责任人'),
        ),
    ]
