# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0015_auto_20160219_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_name',
            field=models.CharField(max_length=127, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contact_telephone',
            field=models.CharField(max_length=127, verbose_name='电话'),
        ),
    ]
