# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 00:59
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0016_auto_20160219_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='预计完成时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='选择项目或特殊事件，默认留空即可', related_name='ticket', to='SupportTicketSystem.Tag', verbose_name='标签'),
        ),
    ]
