# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:58
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0018_auto_20160220_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['scheduled_time', 'level'], 'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='level',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='故障级别'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='默认为当前时间立即开始', verbose_name='计划开始日期'),
        ),
    ]
