# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0019_auto_20160220_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='detail',
            field=models.TextField(blank=True, help_text='任何其他重要信息', null=True, verbose_name='详细信息'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='detail',
            field=models.TextField(blank=True, help_text='任何其他重要信息', null=True, verbose_name='详细信息'),
        ),
    ]
