# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0020_auto_20160222_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='process',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'log': [], 'workflow': []}, verbose_name='处理信息'),
        ),
    ]
