# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0021_auto_20160226_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
    ]
