# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 00:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0023_auto_20160226_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='process',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'log': [], 'workflow': []}, editable=False, verbose_name='处理信息'),
        ),
    ]
