# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:29
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BusinessSystem', '0006_auto_20160220_0121'),
        ('BranchManager', '0007_department_pinyin'),
        ('Equipment', '0006_auto_20160220_0121'),
        ('SupportTicketSystem', '0024_auto_20160227_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位')),
                ('db_active', models.BooleanField(db_index=True, default=True, verbose_name='激活')),
                ('title', models.CharField(max_length=127, verbose_name='标题')),
                ('detail', models.TextField(blank=True, help_text='任何其他重要信息', null=True, verbose_name='详细信息')),
                ('level', models.FloatField(db_index=True, default=0.0, help_text='0-1普通，2-3急，4+特级', verbose_name='级别')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成事件')),
                ('scheduled_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='默认为当前时间立即开始', verbose_name='计划开始日期')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_event', to='SupportTicketSystem.SupportTicketSystemUser',
                                              verbose_name='创建者')),
                ('relevant_business',
                 models.ManyToManyField(blank=True, help_text='涉及的业务系统，没有请留空', related_name='relevant_project', to='BusinessSystem.System', verbose_name='涉及系统')),
                ('relevant_equipment',
                 models.ManyToManyField(blank=True, help_text='涉及的硬件设备类型，请尽量准确，没有请留空', related_name='relevant_project', to='Equipment.EquipmentModel', verbose_name='涉及硬件')),
                ('tag', models.ManyToManyField(blank=True, help_text='选择项目或特殊事件，默认留空即可', related_name='project', to='SupportTicketSystem.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '项目',
                'verbose_name': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位')),
                ('db_active', models.BooleanField(db_index=True, default=True, verbose_name='激活')),
                ('completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成事件')),
                ('department',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_project_event', to='BranchManager.Department', verbose_name='网点/部门')),
            ],
            options={
                'verbose_name_plural': '项目事件',
                'verbose_name': '项目事件',
            },
        ),
    ]
