# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0025_project_projectevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevent',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='SupportTicketSystem.Project', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
