# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0026_projectevent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevent',
            name='process',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'log': [], 'workflow': []}, editable=False, verbose_name='处理信息'),
        ),
    ]
