# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0027_projectevent_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevent',
            name='level',
            field=models.FloatField(db_index=True, default=0.0, help_text='0-1普通，2-3急，4+特级', verbose_name='级别'),
        ),
    ]
