# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SupportTicketSystem', '0028_projectevent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevent',
            name='completed_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_project_event',
                                    to='SupportTicketSystem.SupportTicketSystemUser', verbose_name='完成人'),
        ),
    ]
