# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupportTicketSystem', '0030_projecteventfile_projectfile_ticketfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketfile',
            options={'verbose_name': '工单附件', 'verbose_name_plural': '工单附件'},
        ),
    ]
