# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportTicketSystem', '0031_auto_20160307_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='after_sale_protection',
            field=models.BooleanField(default=False, verbose_name='是否交维保处理'),
        ),
    ]
