# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportTicketSystem', '0032_ticket_after_sale_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='need_completed_by_admin',
            field=models.BooleanField(default=False, verbose_name='是否必须由管理员完成'),
        ),
    ]
