# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportTicketSystem', '0034_auto_20160308_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='wait_admin',
            field=models.BooleanField(default=False, verbose_name='等待管理员完成'),
        ),
    ]
