# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSystem', '0006_auto_20160220_0121'),
        ('Equipment', '0006_auto_20160220_0121'),
        ('SupportTicketSystem', '0036_auto_20160308_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='relevant_business',
            field=models.ManyToManyField(blank=True, to='BusinessSystem.System', verbose_name='涉及系统'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='relevant_equipment',
            field=models.ManyToManyField(blank=True, to='Equipment.EquipmentModel', verbose_name='涉及硬件'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportTicketSystem.SupportTicketSystemUser', verbose_name='指定责任人'),
        ),
    ]
