# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 06:07
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('fqdn', models.CharField(max_length=128, unique=True, verbose_name='(Fully Qualified Domain Name)完全合格域名')),
                ('NetBIOS', models.CharField(max_length=24, unique=True, verbose_name='NetBios name')),
                ('dc_server', models.CharField(max_length=24, unique=True, verbose_name='DC Server Name/IP')),
                ('search_base', models.TextField(default='dc=home,dc=local', verbose_name='搜索限定')),
            ],
            options={
                'verbose_name_plural': '域',
                'verbose_name': '域',
            },
        ),
        migrations.CreateModel(
            name='DomainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('objectSid', models.CharField(max_length=256, unique=True, verbose_name='objectSid')),
                ('cn', models.CharField(max_length=642, verbose_name='Name')),
                ('displayName', models.CharField(max_length=256, verbose_name='Display Name')),
                ('distinguishedName', models.TextField(blank=True, null=True, verbose_name='X500 Distinguished Name')),
                ('givenName', models.CharField(blank=True, max_length=256, null=True, verbose_name='First Name')),
                ('sn', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name')),
                ('initials', models.CharField(blank=True, max_length=256, null=True, verbose_name='Initials')),
                ('mail', models.CharField(blank=True, max_length=256, null=True, verbose_name='E-Mail Address')),
                ('userPrincipalName', models.CharField(blank=True, max_length=256, null=True, verbose_name='Logon Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_user', to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name_plural': 'AD映射用户',
                'verbose_name': 'AD映射用户',
            },
        ),
    ]
