# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainsetting',
            name='connect_pass',
            field=models.CharField(default='1', max_length=128, verbose_name='连接密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainsetting',
            name='connect_user',
            field=models.CharField(default='2', max_length=128, verbose_name='连接用户名'),
            preserve_default=False,
        ),
    ]
