# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:42
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('BranchManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('ip_address', models.GenericIPAddressField(verbose_name='子网地址')),
                ('mask', models.GenericIPAddressField(default='255.255.255.0', verbose_name='子网掩码')),
                ('description', models.TextField(default=' ', max_length=255, verbose_name='详细描述')),
                ('hostname', models.CharField(default=' ', max_length=255, verbose_name='主机名')),
            ],
            options={
                'verbose_name_plural': '主机',
                'verbose_name': '主机',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('subnet_address', models.GenericIPAddressField(verbose_name='子网地址')),
                ('mask', models.GenericIPAddressField(default='255.255.255.0', verbose_name='子网掩码')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('vlan', models.IntegerField(default=1, verbose_name='VLAN ID')),
                ('summary', models.CharField(default=' ', max_length=128, verbose_name='简介')),
                ('description', models.TextField(blank=True, default=' ', max_length=255, verbose_name='详细描述')),
                ('department',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnet', to='BranchManager.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '子网',
                'verbose_name': '子网',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='IPAddress.Subnet', verbose_name='部门'),
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together=set([('subnet_address', 'mask')]),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('ip_address', 'mask')]),
        ),
    ]
