# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0008_auto_20160306_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ping_last_success_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='host',
            name='ping_latest_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
