# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0009_auto_20160306_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='主机名'),
        ),
    ]
