# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0010_auto_20160306_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostname_latest_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
