# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0011_host_hostname_latest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ping_last_success_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='延迟'),
        ),
    ]
