# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0012_auto_20160309_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ping_last_success_fraction_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='丢包率'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ping_last_success_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后ping通'),
        ),
    ]
