# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0013_auto_20160309_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='latest_scan_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后扫描事件'),
        ),
    ]
