# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0014_host_latest_scan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='hostname_latest_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ping_latest_time',
        ),
    ]
