# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:41
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0016_auto_20160310_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='latest_scan_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后扫描时间'),
        ),
    ]
