# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0017_subnet_latest_scan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ping_last_success_fraction_loss',
        ),
    ]
