# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0021_host_latest_ping_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='latest_ping_time',
            new_name='ping_latest_time',
        ),
        migrations.AddField(
            model_name='host',
            name='ping_stdout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
