# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0032_host_ping_stdout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='latest_scan_time',
        ),
        migrations.AddField(
            model_name='host',
            name='reverse_latest_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后一次主机名反查日期'),
        ),
    ]
