# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPAddress', '0034_auto_20160318_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='latest_ping_time',
            new_name='ping_latest_time',
        ),
    ]
