# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BusinessSystem', '0005_system_db_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='db_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='激活'),
        ),
    ]
