# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 06:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesystemuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_system_user', to=settings.AUTH_USER_MODEL, verbose_name='对应用户'),
        ),
    ]
