# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 14:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0003_auto_20160124_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='AttendanceSystem.AttendanceSystemUser', verbose_name='用户'),
        ),
    ]
