# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0004_auto_20160125_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='first_time',
            field=models.TimeField(auto_now_add=True, verbose_name='首次时间'),
        ),
    ]
