# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0005_auto_20160126_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
