# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0006_auto_20160126_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_time',
            field=models.TimeField(null=True, verbose_name='最后一次的时间'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('user', 'date')]),
        ),
    ]
