# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0007_auto_20160126_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='first_time',
            field=models.TimeField(null=True, verbose_name='首次时间'),
        ),
    ]
