# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0010_auto_20160128_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesystemuser',
            name='on_duty',
            field=models.BooleanField(default=False, verbose_name='在岗'),
        ),
    ]
