# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0012_auto_20160215_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='first_time_local',
            field=models.CharField(default=' ', max_length=127, verbose_name='签到地点'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_time_local',
            field=models.CharField(default=' ', max_length=127, verbose_name='签退地点'),
        ),
    ]
