# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AttendanceSystem', '0013_auto_20160216_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='first_time_local',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_time_local',
        ),
        migrations.AddField(
            model_name='entry',
            name='first_time_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='首次IP'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_time_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='签退IP'),
        ),
    ]
