# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceSystem', '0017_auto_20160220_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='first_time_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='首次IP'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_time_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='签退IP'),
        ),
    ]
