# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:34
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, verbose_name='设备品牌')),
            ],
            options={
                'verbose_name_plural': '设备品牌',
                'verbose_name': '设备品牌',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, verbose_name='设备型号')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.EquipmentBrand', verbose_name='品牌')),
            ],
            options={
                'verbose_name_plural': '设备型号',
                'verbose_name': '设备型号',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('title', models.CharField(max_length=255, verbose_name='设备类型')),
            ],
            options={
                'verbose_name_plural': '设备类型',
                'verbose_name': '设备类型',
            },
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.EquipmentType', verbose_name='设备类型'),
        ),
    ]
