# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Equipment', '0003_auto_20160218_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbrand',
            name='for_short',
            field=models.CharField(default=' ', max_length=24, verbose_name='缩写'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='for_short',
            field=models.CharField(default=' ', max_length=24, verbose_name='缩写'),
        ),
    ]
