# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Equipment', '0004_auto_20160218_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbrand',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='db_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
    ]
