# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:51
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(default=0.0, verbose_name='顺位')),
                ('filename', models.CharField(editable=False, max_length=255, null=True, verbose_name='文件名')),
                ('content_type', models.CharField(editable=False, max_length=127, null=True, verbose_name='Content Type')),
                ('orig_file', models.FileField(help_text='选择一个文件并上传', upload_to='attachment/25e6cdfa-92be-412b-b885-fda9293d6e2b/', verbose_name='文件')),
                ('md5sum', models.CharField(editable=False, max_length=36, null=True)),
            ],
            options={
                'verbose_name_plural': '附件',
                'verbose_name': '附件',
            },
        ),
    ]
