# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Equipment', '0001_initial'),
        ('DownloadCenter', '0002_auto_20160202_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Equipment.EquipmentBrand', verbose_name='品牌'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Equipment.EquipmentType', verbose_name='设备类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='attachment/fe644291-26ea-4768-a968-b43b357aa199/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='driver/30e7be23-fdad-461a-a590-4f6085781e3e/', verbose_name='文件'),
        ),
    ]
