# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0003_auto_20160202_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='attachment/11dcab21-6942-4980-b651-aa3722cd4d0b/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='driver/487a57cd-337d-4dbb-85be-1bdfdf1a6c23/', verbose_name='文件'),
        ),
    ]
