# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0004_auto_20160202_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='attachment/a4f9000d-3c13-49f7-815b-d38a7573bac0/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='driver/79b909f8-6d0a-430b-8372-0748f8c97189/', verbose_name='文件'),
        ),
    ]
