# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0005_auto_20160202_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='attachment/0dd218e5-68ae-4605-b3b9-f3422d55daa9/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orig_file',
            field=models.FileField(help_text='选择一个文件并上传', upload_to='driver/c4633afb-dfaa-4d28-b8af-1f79d628fbbf/', verbose_name='文件'),
        ),
    ]
