# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:39
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0011_businesssoftware_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='businesssoftware',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='businesssoftware',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='businesssoftware',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='businesssoftware',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='db_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='db_manual_order',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='顺位'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='db_modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='db_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
