# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0015_auto_20160220_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='manual',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='driver',
            name='manual',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
    ]
