# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 14:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DownloadCenter', '0016_auto_20160303_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssoftware',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='BusinessSystem.System', verbose_name='业务系统'),
        ),
    ]
