# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadCenter', '0017_auto_20160305_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='equipment_model',
            field=models.ManyToManyField(related_name='driver', to='Equipment.EquipmentModel', verbose_name='适配设备型号'),
        ),
    ]
