# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DayBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPCLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('db_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改日期')),
                ('db_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('db_manual_order', models.FloatField(db_index=True, default=0.0, editable=False, verbose_name='顺位')),
                ('db_active', models.BooleanField(db_index=True, default=True, verbose_name='激活')),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(editable=False, verbose_name='历史')),
            ],
            options={
                'ordering': ['db_manual_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='internetpc',
            name='history',
        ),
        migrations.AddField(
            model_name='internetpclog',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayBook.InternetPC'),
        ),
    ]
