# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayBook', '0003_auto_20160326_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetpc',
            name='manager',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='管理者'),
        ),
    ]
