# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayBook', '0004_internetpc_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetpc',
            name='way',
            field=models.CharField(choices=[('adsl', 'ADSL'), ('eth', '代理内网')], default='eth', max_length=128, verbose_name='上网方式'),
        ),
    ]
